const crypto=require('node:crypto');
const SENSITIVE_KEY=/(authorization|api[-_]?key|token|secret|password|cookie|session|prompt|input|output|content)/i;
const SECRET_VALUE=/(bearer\s+[a-z0-9._-]+|sk-[a-z0-9_-]{12,}|-----BEGIN [A-Z ]+PRIVATE KEY-----)/ig;
function redact(value,key=''){if(SENSITIVE_KEY.test(key))return'[REDACTED]';if(Array.isArray(value))return value.map((item)=>redact(item));if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).map(([name,item])=>[name,redact(item,name)]));if(typeof value==='string')return value.replace(SECRET_VALUE,'[REDACTED]');return value;}
function otlpValue(value={}){if('stringValue'in value)return value.stringValue;if('boolValue'in value)return value.boolValue;if('intValue'in value)return Number(value.intValue);if('doubleValue'in value)return value.doubleValue;if(value.arrayValue)return(value.arrayValue.values||[]).map(otlpValue);if(value.kvlistValue)return Object.fromEntries((value.kvlistValue.values||[]).map((item)=>[item.key,otlpValue(item.value)]));return null;}
function attributes(items=[]){return Object.fromEntries(items.map((item)=>[item.key,otlpValue(item.value)]));}
function nanosToIso(value){try{return new Date(Number(BigInt(value||0)/1000000n)).toISOString();}catch{return new Date().toISOString();}}
function durationMs(start,end){try{const delta=BigInt(end||0)-BigInt(start||0);return delta>0?Number(delta/1000000n):0;}catch{return 0;}}
function parseOtlp(payload){const groups=new Map();for(const resourceSpan of Array.isArray(payload?.resourceSpans)?payload.resourceSpans:[]){const resource=attributes(resourceSpan.resource?.attributes||[]);const service=String(resource['service.name']||'unknown');for(const scopeSpan of resourceSpan.scopeSpans||[]){for(const span of scopeSpan.spans||[]){const traceId=String(span.traceId||span.trace_id||'');const spanId=String(span.spanId||span.span_id||'');if(!/^[a-fA-F0-9]{16,32}$/.test(traceId)||!/^[a-fA-F0-9]{8,16}$/.test(spanId))continue;const attrs=redact({...resource,...attributes(span.attributes||[])});const item={trace_id:traceId,span_id:spanId,parent_span_id:String(span.parentSpanId||span.parent_span_id||'')||null,name:String(span.name||'unnamed').slice(0,255),kind:String(span.kind||'unspecified').slice(0,40),attrs,status:Number(span.status?.code||0)>=2?'error':'ok',started_at:nanosToIso(span.startTimeUnixNano||span.start_time_unix_nano),duration_ms:durationMs(span.startTimeUnixNano||span.start_time_unix_nano,span.endTimeUnixNano||span.end_time_unix_nano),input_tokens:Number(attrs['gen_ai.usage.input_tokens']||attrs['llm.usage.prompt_tokens']||0),output_tokens:Number(attrs['gen_ai.usage.output_tokens']||attrs['llm.usage.completion_tokens']||0),cost_usd:Number(attrs['gen_ai.cost.usd']||attrs['llm.cost.usd']||0),service_name:service};if(!groups.has(traceId))groups.set(traceId,[]);groups.get(traceId).push(item);}}}return[...groups.entries()].map(([trace_id,spans])=>({trace_id,service_name:spans[0]?.service_name||'unknown',spans,duration_ms:Math.max(0,...spans.map((span)=>span.duration_ms)),status:spans.some((span)=>span.status==='error')?'error':'ok',total_cost_usd:spans.reduce((sum,span)=>sum+span.cost_usd,0)}));}
function evaluationMetrics(cases,threshold,baselinePassRate){const passed=cases.filter((item)=>item.passed).length;const total=cases.length;const passRate=total?passed/total:0;const avgLatency=total?cases.reduce((sum,item)=>sum+Number(item.latency_ms||0),0)/total:0;const regression=Number.isFinite(baselinePassRate)?passRate-baselinePassRate:null;return{total,passed,failed:total-passed,pass_rate:passRate,average_latency_ms:avgLatency,regression,gate_status:passRate>=threshold&&(regression===null||regression>=0)?'passed':'failed'};}
function datasetHash(cases){return crypto.createHash('sha256').update(JSON.stringify(cases)).digest('hex');}
module.exports={datasetHash,evaluationMetrics,parseOtlp,redact};
